FROM qore/qbus2:bullseye

COPY docker /qore
RUN mkdir /build && cd /build && cmake ../qore/flow && make install

FROM bitnami/minideb:bullseye

RUN apt-get update && apt-get install -y \
  mariadb-client-10.5 \
  libcrypt1 \
  && rm -rf /var/lib/apt/lists/*
  
COPY --from=0 /opt .

WORKDIR /mods

ENTRYPOINT ["/mods/qbus_mod_flow"]
CMD ["-d", "socket:127.0.0.1:33340"]
