FROM qore/qbus2:bookworm

COPY docker /qore
RUN mv /qore/2fd0e638-9489-410f-9d38-dbcacd5b15b6.txt /qore/CMakeLists.txt \
 && mkdir /qore/build \
 && cd /qore/build \
 && cmake .. \
 && make install

RUN chmod -R 777 /qore/build/image_gen

RUN ls -alR /qore/build/image_gen

FROM scratch

ENV PATH="/bin;/lib;/lib64"
ENV LD_LIBRARY_PATH="/lib64;/usr/lib/gcc/x86_64-pc-linux-gnu/12/"

COPY --from=0 /qore/build/image_gen .

WORKDIR /bin
USER 1000:1000

HEALTHCHECK CMD ["/bin/healthcheck"]
ENTRYPOINT ["/bin/execsec", "/bin/qbus_mod_flow.sec"]
