FROM qore/qbus:buster

COPY docker /qore
RUN mkdir /build && cd /build && cmake ../qore/auth && make install

FROM bitnami/minideb:buster

RUN apt-get update && apt-get install -y \
  libmariadb-dev-compat \
  libssl-dev \
  && rm -rf /var/lib/apt/lists/*
  
COPY --from=0 /opt .

WORKDIR /mods

ENTRYPOINT ["/mods/qbus_mod_auth"]
CMD ["-d", "socket:127.0.0.1:33340"]
