FROM qore/qbus:bullseye

COPY docker /qore
RUN mkdir /qore/build && cd /qore/build && cmake .. && make install

FROM --platform=linux/amd64 bitnami/minideb:bullseye

RUN apt-get update && apt-get install -y \
  libmariadb-dev-compat \
  libssl-dev \
  valgrind \
  && rm -rf /var/lib/apt/lists/*

COPY --from=0 /opt .

WORKDIR /mods
ENTRYPOINT ["valgrind", "/mods/qbus_mod_auth"]
