FROM qore/qbus:bookworm

COPY docker /qore
RUN mv /qore/ccd79834-4619-4f50-95b0-81fa314ab6be.txt /qore/CMakeLists.txt \
 && mkdir /qore/build \
 && cd /qore/build \
 && cmake .. \
 && make install

FROM scratch

ENV PATH="/bin;/lib;/lib64"
ENV LD_LIBRARY_PATH="/lib64;/usr/lib/gcc/x86_64-pc-linux-gnu/12/"

COPY --from=0 /qore/build/image_gen .

WORKDIR /bin
ENTRYPOINT ["/bin/qbus_mod_auth"]
