FROM alpine:3.14

RUN apk add --no-cache \
  make \
  cmake \
  musl-dev \
  libexecinfo-dev \
  linux-headers \
  gcc \
  g++ \
  mariadb-dev \
  sqlite-dev \
  pcre-dev \
  curl-dev \
  libressl-dev \
  libuuid \
  fts-dev

ARG CACHEBUST=1
