FROM debian:12-slim

RUN apt-get update && apt-get install -y \
  gcc \
  g++ \
  cmake \
  default-libmysqlclient-dev \
  libsqlite3-dev \
  libpcre3-dev \
  libcurl4-openssl-dev \
  libssl-dev \
  libnss3 \
  locales \
  libglib2.0-0 \
  uuid-dev \
  libxml2-dev \
  && rm -rf /val/lib/apt/lists/*

ARG CACHEBUST=1
