FROM debian:12-slim

RUN apt-get update && apt-get install -y \
  gcc \
  g++ \
  cmake \
  default-libmysqlclient-dev \
  libsqlite3-dev \
  libpcre3-dev \
  libcurl4-openssl-dev \
  libssl-dev \
  uuid-dev

ARG CACHEBUST=1
