FROM --platform=linux/amd64 debian:bookworm-slim

RUN apt-get update && apt-get install -y \
  build-essential \
  make \
  autoconf \
  automake \
  libtool \
  gcc \
  g++ \
  git \
  cmake \
  zip \
  zlib1g-dev \
  gawk \
  default-libmysqlclient-dev \
  libsqlite3-dev \
  libpcre3-dev \
#  libcurl4-openssl-dev \
  libssl-dev \
  libnss3 \
  locales \
  libglib2.0-0 \
  uuid-dev \
  libxml2-dev \
  libpsl-dev \
  libzip-dev \
  valgrind \
  strace \
  && rm -rf /val/lib/apt/lists/*

# clone current libcurl
RUN git clone https://github.com/curl/curl.git /usr/src/curl

# install libcurl from sources, see issue
# https://github.com/curl/curl/issues/18448
RUN cd /usr/src/curl \
 && autoreconf -fi \
 && ./configure --with-openssl --disable-socketpair \
 && make \
 && make install

ARG CACHEBUST=1
