FROM bitnami/minideb:buster

RUN apt-get update && apt-get install -y \
  cmake \
  gcc \
  g++ \
  default-libmysqlclient-dev \
  libsqlite3-dev \
  libpcre3-dev \
  libcurl4-openssl-dev \
  libssl-dev \
  uuid-dev \
  && rm -rf /var/lib/apt/lists/*

ARG CACHEBUST=1
ADD . /opt/modules/

RUN ls /opt/modules/
RUN cat /opt/modules/adbl_default.json
