FROM qore/qbus:buster

COPY docker /qore
RUN mkdir /build && cd /build && cmake ../qore/webs && make install

FROM bitnami/minideb:buster

RUN apt-get update && apt-get install -y \
  libssl-dev \
  && rm -rf /var/lib/apt/lists/*
  
COPY --from=0 /opt .

WORKDIR /mods

RUN groupadd -r qbus    -g 1000 && \
useradd -u 1000 -r -g qbus -d /app -s /sbin/nologin -c "container user" qbus 

USER qbus

ENTRYPOINT ["/mods/qbus_mod_webs"]
CMD ["-d", "socket:127.0.0.1:33340"]
