FROM qore/qbus:buster

COPY docker /qore
RUN mkdir /build && cd /build && cmake ../qore/webs && make install

FROM bitnami/minideb:buster

RUN apt-get update && apt-get install -y \
  libssl-dev \
  && rm -rf /var/lib/apt/lists/*
  
COPY --from=0 /opt .

WORKDIR /modules

ENTRYPOINT ["/modules/qbus_mod_webs"]
CMD ["-d", "socket:127.0.0.1:33340"]
