FROM qore/qbus2:bookworm

COPY docker /qore
RUN mv /qore/cdfb649e-03cf-47cd-ba98-16aae68a52a1.txt /qore/CMakeLists.txt \
 && mkdir /qore/build \
 && cd /qore/build \
 && cmake .. \
 && make install

FROM scratch

ENV PATH="/bin;/lib;/lib64"
ENV LD_LIBRARY_PATH="/lib64;/usr/lib/gcc/x86_64-pc-linux-gnu/12/"

COPY --from=0 /qore/build/image_gen .

WORKDIR /bin

HEALTHCHECK CMD ["/bin/healthcheck"]
ENTRYPOINT ["/bin/qbus_mod_jobs"]
